### ISSUE TITLE
More-info: update frequency dropdown

### ISSUE THREAD

**Issue by meghanhade** [mapzen/mobility-on-demand-sandbox-contributions#110]
Shows selected choice twice.

**Comment by mkong0216** [comment]
This happens with the license dropdown as well so I will fix it in both places.

**Comment by souperneon** [comment]
@mkong0216 just make sure they are consistent either way. If the selected option appears twice is fine.

**Comment by mkong0216** [comment]
I'm thinking that having it show twice is fine since the repeated one in the dropdown is highlighted to indicate that its been chosen, so I'm going to close this issue. If anyone wants it to not show the selected choice twice feel free to reopen and I will fix it.
