### ISSUE TITLE
set up form validation on data input

### ISSUE THREAD

**Issue by meghanhade** [mapzen/mobility-on-demand-sandbox-contributions#31]

**Comment by hanbyul-here** [comment]
Since Semantic UI offers [various levels of form validations](https://semantic-ui.com/behaviors/form.html) It would be nice if we can take advantage of this.

**Comment by hanbyul-here** [comment]
Sadly Semantic UI validations wouldn't really mount to how Ember data works. (ex. even if we clear the data using semantic UI validation, ember data wouldn't really know unless we make every conneciton between them) 

I am browsing some options in Ember world.
