### ISSUE TITLE
Outline possible schema mappings

### ISSUE THREAD

**Issue by dianashk** [mapzen/mobility-on-demand-sandbox-contributions#34]
We need to list out all possible types of schema mappings supported by the OA meta-files.

There are at least 3 types:
- __1:1__  e.g. `src:STR` -> `oa:street`
- __1:*__   e.g. `src:PRE+src:STR+src:POST` -> `oa:street`
- __1:regex__  e.g. `src:ADDR` -> `oa:number` AND `src:ADDR` -> `oa:street`

What other types can we think of?

**Comment by migurski** [comment]
There are a few functions other than regex, defined here: https://github.com/openaddresses/openaddresses/blob/master/ATTRIBUTE_FUNCTIONS.md

**Comment by dianashk** [comment]
This is very helpful! Thanks @migurski! 🌻

**Comment by meghanhade** [comment]
I investigated the frequency of use of the various functions listed in the doc @migurski shared, to help understand what to prioritize in the UI. Please let me know if you see any problems with the way I'm running these counts (all run within the openaddresses/sources directory), or ways they could be improved.

**Total file count:**
`grep -ro '\"coverage\": {' * | wc -l`
Total matches:  2179

**Join**
Looking for: `"function": "join",`
`grep -ro '\"function\": \"join\"' * | wc -l`
Total matches:  205

**Format**
Looking for: `"function": "format",`
`grep -ro '\"function\": \"format\"' * | wc -l`
Total matches:  16

**Extraction Functions**
Looking for: `"function": "prefixed_number",`
`grep -ro '\"function\": \"prefixed_number\"' * | wc -l`
Total matches:  62

Looking for: `"function": "postfixed_street",`
`grep -ro '\"function\": \"postfixed_street\"' * | wc -l`
Total matches:  56

Looking for: `"function": "remove_prefix",`
`grep -ro '\"function\": \"remove_prefix\"' * | wc -l`
Total matches:  18

Looking for: `"function": "remove_postfix",`
grep -ro '\"function\": \"remove_postfix\"' * | wc -l
Total matches:  2

**Chain**
Looking for: `"function": "chain",`
`grep -ro '\"function\": \"chain\"' * | wc -l`
Total matches:  0

**Reg Exp**
Looking for: `"function": "regexp",`
`grep -ro '\"function\": \"regexp\"' * | wc -l`
Total matches:  1048

With the approach above, `"function": "regexp",` was counted multiple times in one file. This is the number of files with any use of `"function": "regexp",`:
`grep -rol '\"function\": \"regexp\"' * | wc -l`
Total matches:  508

There was one other different count when counting this way:

Looking for: `"function": "join",`
`grep -rol '\"function\": \"join\"' * | wc -l`
Total matches:  204

@trescube do you know why the count for `regexp` is so high? Was it used more frequently in the beginning before these other functions were added? Is it still used frequently?
