### ISSUE TITLE
Make onchange debounce with power-select

### ISSUE THREAD

**Issue by hanbyul-here** [mapzen/mobility-on-demand-sandbox-contributions#51]
- related PR: https://github.com/mapzen/mobility-on-demand-sandbox-contributions/pull/48
- Search is implemented without debounce option, we probably want to do this especially if we are hitting the server directly with user's input

**Comment by meghanhade** [comment]
Info for debouncing power select: http://www.ember-power-select.com/cookbook/debounce-searches
