### ISSUE TITLE
Style improvements

### ISSUE THREAD

**Issue by meghanhade** [mapzen/mobility-on-demand-sandbox-contributions#56]
- Font: Lato
- Bold 900 for heading
- Regular #FFF for body
- Use same h1-h5 hierarchy from styleguide:
  - h1: 48
  - h2: 36
  - h3: 24
  - h4: 20
  - h5: 16
  - body text: 16
- Use colors:
  - #134045 
  - #508478

**Comment by mkong0216** [comment]
Using openaddress colors instead of above mentioned colors as well as 'Open Sans' 
Everything else is implemented in the stylesheet.
