### ISSUE TITLE
Create list of common licenses

### ISSUE THREAD

**Issue by meghanhade** [mapzen/mobility-on-demand-sandbox-contributions#68]
-  include URLs for licenses
- check if it's ok to send license name to OA, or if URL is required
- text box for pasting URL if the license their data uses isn't on list

**Comment by meghanhade** [comment]
Is there a character limit for the user-submitted URL?

**Comment by dianashk** [comment]
I don't believe there's a character limit.

**Comment by dianashk** [comment]
Great source of information about open data licensing: https://project-open-data.cio.gov/open-licenses/
They list the following licenses which we could just borrow (with proper attribution)

### Open Licenses

- Open Data Commons Attribution License (ODC-By), e.g. `"license":"http://opendatacommons.org/licenses/by/1.0/"`
- Open Data Commons Open Database License (ODbL), e.g. `"license":"http://opendatacommons.org/licenses/odbl/1.0/"`
- Creative Commons Attribution (CC BY), e.g. `"license":"https://creativecommons.org/licenses/by/4.0/"`
- Creative Commons Attribution-ShareAlike (CC BY-SA), e.g. `"license":"https://creativecommons.org/licenses/by-sa/4.0/"`
- GNU Free Documentation License, e.g. `"license":"http://www.gnu.org/licenses/fdl-1.3.en.html"`
