### ISSUE TITLE
Set up development environment

### ISSUE THREAD

**Issue by hanbyul-here** [mapzen/mobility-on-demand-sandbox-contributions#7]
- [x] set up the linter (It seems that Ember CLI sets up jshint as a default linter. I will set up the command to run this and make this part of the test)
- [x] set up local test environment.
- [x] set up Netlify for easy preview (I am not sure it would be worth doing it separately from CircleCI. but would love to set up just to see what benefits it would bring. We can use this preview until we know where to deploy.) 
- [x] set up CircleCI hook for tests and the deployment.

**Comment by meghanhade** [comment]
- [ ] set up s3 bucket
