### ISSUE TITLE
Use red asterisk to mark required fields, add key on each page.

### ISSUE THREAD

**Issue by meghanhade** [mapzen/mobility-on-demand-sandbox-contributions#73]

**Comment by meghanhade** [comment]
More-info
- [ ] If license = yes, require license selection from dropdown or url

**Comment by mkong0216** [comment]
@meghanhade would the first bullet ("displays message about requirements if user clicks next without providing url or upload") be a form validation thing? I see in the nav-button component file that there's something called a `changeset` and if there's an error, an error message is automatically generated?
