### ISSUE TITLE
Copy Polish

### ISSUE THREAD

**Issue by meghanhade** [mapzen/mobility-on-demand-sandbox-contributions#84]
This issue is a place to gather needed copy additions/edits and ui polish 

Copy:
- [x] Add text for review page's `cancel` button explaining that user will start over

**Comment by mkong0216** [comment]
@meghanhade : should I leave this open for future issues regarding copy additions/edits and ui polish, or should I close it now since pull #101 added the cancel modal?

**Comment by meghanhade** [comment]
@mkong0216 thanks for checking -- we should keep this open and add to the list as ui polish issues surface.

**Comment by souperneon** [comment]
Let's make this one just for copy @meghanhad, since i totally ignored it and made a new one :(

**Comment by souperneon** [comment]
- [ ] Capitalization in the frequency dropdown
- [ ] Change 'Remove extraction' to 'Undo' with Undo icon

Sorry forgot to post ^^
